msg:
    internal: message from inside app
server:
    port: 8888
spring:
    cloud:
        config:
            server:
                git:
                    uri: D:/Poomalai/Project/ms/PropFileFor-SpringCloudConfigServer.git
